# Dockerfile para TerceroNestJs - Desarrollo
FROM node:20-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias de desarrollo
RUN npm install --legacy-peer-deps

# Exponer puerto
EXPOSE 3001

# Variables de entorno para desarrollo
ENV NODE_ENV=development
ENV PORT=3001

# Comando por defecto para desarrollo con watch mode
CMD ["npm", "run", "start:dev"]
