from marshmallow import Schema, fields


class ContactoCreateSchema(Schema):
    id_tercero = fields.UUID(required=True)
    apellidos_etiqueta = fields.Str(allow_none=True)
    nombre = fields.Str(allow_none=True)
    titulo_cortesia = fields.Str(allow_none=True)
    puesto_trabajo = fields.Str(allow_none=True)
    direccion = fields.Str(allow_none=True)
    codigo_postal = fields.Str(allow_none=True)
    poblacion = fields.Str(allow_none=True)
    id_pais = fields.UUID(allow_none=True)
    id_provincia = fields.UUID(allow_none=True)
    telefono_trabajo = fields.Str(allow_none=True)
    telefono_particular = fields.Str(allow_none=True)
    movil = fields.Str(allow_none=True)
    fax = fields.Str(allow_none=True)
    correo = fields.Str(allow_none=True)
    visibilidad = fields.Str(allow_none=True)
    fecha_nacimiento = fields.Date(allow_none=True)
    alerta_cumpleanos = fields.Bool(load_default=False)
    estado = fields.Bool(load_default=True)


class ContactoUpdateSchema(Schema):
    apellidos_etiqueta = fields.Str(allow_none=True)
    nombre = fields.Str(allow_none=True)
    titulo_cortesia = fields.Str(allow_none=True)
    puesto_trabajo = fields.Str(allow_none=True)
    direccion = fields.Str(allow_none=True)
    codigo_postal = fields.Str(allow_none=True)
    poblacion = fields.Str(allow_none=True)
    id_pais = fields.UUID(allow_none=True)
    id_provincia = fields.UUID(allow_none=True)
    telefono_trabajo = fields.Str(allow_none=True)
    telefono_particular = fields.Str(allow_none=True)
    movil = fields.Str(allow_none=True)
    fax = fields.Str(allow_none=True)
    correo = fields.Str(allow_none=True)
    visibilidad = fields.Str(allow_none=True)
    fecha_nacimiento = fields.Date(allow_none=True)
    alerta_cumpleanos = fields.Bool(allow_none=True)
    estado = fields.Bool(allow_none=True)


class ContactoResponseSchema(Schema):
    id_contacto = fields.UUID()
    id_tercero = fields.UUID()
    apellidos_etiqueta = fields.Str(allow_none=True)
    nombre = fields.Str(allow_none=True)
    titulo_cortesia = fields.Str(allow_none=True)
    puesto_trabajo = fields.Str(allow_none=True)
    direccion = fields.Str(allow_none=True)
    codigo_postal = fields.Str(allow_none=True)
    poblacion = fields.Str(allow_none=True)
    id_pais = fields.UUID(allow_none=True)
    id_provincia = fields.UUID(allow_none=True)
    telefono_trabajo = fields.Str(allow_none=True)
    telefono_particular = fields.Str(allow_none=True)
    movil = fields.Str(allow_none=True)
    fax = fields.Str(allow_none=True)
    correo = fields.Str(allow_none=True)
    visibilidad = fields.Str(allow_none=True)
    fecha_nacimiento = fields.Date(allow_none=True)
    alerta_cumpleanos = fields.Bool()
    estado = fields.Bool()
    created_at = fields.DateTime(allow_none=True)
    updated_at = fields.DateTime(allow_none=True)
