from utils.db import db
from sqlalchemy.sql import func

class Tercero(db.Model):
    __tablename__ = 'tercero'
    id_tercero = db.Column(db.Integer, primary_key=True)
    entity = db.Column(db.Integer, nullable=False, default=1)
    ref_ext = db.Column(db.String(60), unique=True)
    ref_int = db.Column(db.String(60))
    parent = db.Column(db.Integer, db.ForeignKey('tercero.id_tercero', ondelete='SET NULL'))
    statut = db.Column(db.SmallInteger, default=0)
    status = db.Column(db.SmallInteger, default=1)
    code_client = db.Column(db.String(24))
    code_fournisseur = db.Column(db.String(24))
    code_compta = db.Column(db.String(24))
    code_compta_fournisseur = db.Column(db.String(24))
    ruc = db.Column(db.String(13))
    fk_typent = db.Column(db.Integer)
    fk_forme_juridique = db.Column(db.Integer)
    siren = db.Column(db.String(9))
    siret = db.Column(db.String(14))
    ape = db.Column(db.String(5))
    capital = db.Column(db.Numeric(14,2))
    fk_currency = db.Column(db.Integer)
    nombre = db.Column(db.String(150), nullable=False)
    direccion = db.Column(db.String(255))
    zip = db.Column(db.String(10))
    town = db.Column(db.String(100))
    fk_departement = db.Column(db.Integer)
    fk_pays = db.Column(db.Integer)
    phone = db.Column(db.String(20))
    fax = db.Column(db.String(20))
    email = db.Column(db.String(128))
    url = db.Column(db.String(255))
    mode_reglement = db.Column(db.Integer)
    cond_reglement = db.Column(db.Integer)
    tva_intra = db.Column(db.String(32))
    localtax1_assuj = db.Column(db.Boolean)
    localtax2_assuj = db.Column(db.Boolean)
    remise_client = db.Column(db.Numeric(6,2))
    price_level = db.Column(db.SmallInteger, default=1)
    outstanding_limit = db.Column(db.Numeric(14,2))
    barcode = db.Column(db.String(50))
    fk_barcode_type = db.Column(db.Integer)
    default_lang = db.Column(db.String(5))
    logo = db.Column(db.LargeBinary)
    canvas = db.Column(db.Text)
    import_key = db.Column(db.String(14))
    es_prospecto = db.Column(db.Boolean, nullable=False, default=False)
    es_cliente = db.Column(db.Boolean, nullable=False, default=False)
    customer_rank = db.Column(db.Integer, nullable=False, default=0)
    supplier_rank = db.Column(db.Integer, nullable=False, default=0)
    create_uid = db.Column(db.Integer, db.ForeignKey('usuario.id_usuario'), nullable=False)
    create_date = db.Column(db.DateTime, nullable=False, server_default=func.now())
    write_uid = db.Column(db.Integer, db.ForeignKey('usuario.id_usuario'))
    write_date = db.Column(db.DateTime) 