"""Catálogo de cuentas contables por defecto y códigos sugeridos plan EC-SUPERCIAS."""

# tipo_operacion único por empresa (UNIQUE id_empresa, tipo_operacion)
CUENTAS_DEFECTO_CATALOGO = [
    # Terceros | Usuarios
    {'tipo_operacion': 'TERCERO_CLIENTE', 'seccion': 'TERCEROS_USUARIOS',
     'label': 'Cuenta utilizada para terceros "clientes"',
     'codigo_cuenta': '10102050101'},
    {'tipo_operacion': 'TERCERO_PROVEEDOR', 'seccion': 'TERCEROS_USUARIOS',
     'label': 'Cuenta utilizada para terceros "proveedores"',
     'codigo_cuenta': '20103'},
    {'tipo_operacion': 'TERCERO_USUARIO', 'seccion': 'TERCEROS_USUARIOS',
     'label': 'Cuenta utilizada por defecto para terceros "usuarios"',
     'codigo_cuenta': '20108'},
    # Producto
    {'tipo_operacion': 'PRODUCTO_VENTA_NACIONAL', 'seccion': 'PRODUCTO',
     'label': 'Cuenta predeterminada para productos vendidos (nacional)',
     'codigo_cuenta': '40101'},
    {'tipo_operacion': 'PRODUCTO_VENTA_EXPORTACION', 'seccion': 'PRODUCTO',
     'label': 'Cuenta predeterminada para productos vendidos y exportados',
     'codigo_cuenta': '40101'},
    {'tipo_operacion': 'PRODUCTO_COMPRA_NACIONAL', 'seccion': 'PRODUCTO',
     'label': 'Cuenta predeterminada para productos comprados (nacional)',
     'codigo_cuenta': '50101'},
    {'tipo_operacion': 'PRODUCTO_COMPRA_IMPORTACION', 'seccion': 'PRODUCTO',
     'label': 'Cuenta predeterminada para productos comprados e importados',
     'codigo_cuenta': '50101'},
    # Servicio
    {'tipo_operacion': 'SERVICIO_VENTA_NACIONAL', 'seccion': 'SERVICIO',
     'label': 'Cuenta predeterminada para servicios vendidos (nacional)',
     'codigo_cuenta': '40102'},
    {'tipo_operacion': 'SERVICIO_VENTA_EXPORTACION', 'seccion': 'SERVICIO',
     'label': 'Cuenta predeterminada para servicios vendidos y exportados',
     'codigo_cuenta': '40102'},
    {'tipo_operacion': 'SERVICIO_COMPRA_NACIONAL', 'seccion': 'SERVICIO',
     'label': 'Cuenta predeterminada para servicios comprados (nacional)',
     'codigo_cuenta': '50202'},
    {'tipo_operacion': 'SERVICIO_COMPRA_IMPORTACION', 'seccion': 'SERVICIO',
     'label': 'Cuenta predeterminada para servicios comprados e importados',
     'codigo_cuenta': '50202'},
    # Otros
    {'tipo_operacion': 'IVA_VENTA', 'seccion': 'OTROS',
     'label': 'Cuenta predeterminada para IVA en ventas',
     'codigo_cuenta': '2010701'},
    {'tipo_operacion': 'IVA_COMPRA', 'seccion': 'OTROS',
     'label': 'Cuenta predeterminada para IVA en compras',
     'codigo_cuenta': '1010501'},
    {'tipo_operacion': 'IVA_PAGO', 'seccion': 'OTROS',
     'label': 'Cuenta predeterminada para pago de IVA',
     'codigo_cuenta': '2010701'},
    {'tipo_operacion': 'TRANSITORIA_BANCARIA', 'seccion': 'OTROS',
     'label': 'Cuenta transitoria para transferencias bancarias',
     'codigo_cuenta': '1010103'},
    {'tipo_operacion': 'DONACION', 'seccion': 'OTROS',
     'label': 'Cuenta para registro de donaciones',
     'codigo_cuenta': '30605'},
    {'tipo_operacion': 'PRESTAMO_CAPITAL', 'seccion': 'OTROS',
     'label': 'Cuenta predeterminada para capital (préstamos)',
     'codigo_cuenta': '201030101'},
    {'tipo_operacion': 'PRESTAMO_INTERES', 'seccion': 'OTROS',
     'label': 'Cuenta predeterminada para intereses (préstamos)',
     'codigo_cuenta': '2010605'},
    {'tipo_operacion': 'PRESTAMO_SEGURO', 'seccion': 'OTROS',
     'label': 'Cuenta predeterminada para seguro (préstamos)',
     'codigo_cuenta': '2010501'},
    {'tipo_operacion': 'FONDOS_SIN_ASIGNAR', 'seccion': 'OTROS',
     'label': 'Cuenta para fondos recibidos o pagados sin asignar',
     'codigo_cuenta': '1010101'},
    # Anticipos
    {'tipo_operacion': 'ANTICIPO_CLIENTE', 'seccion': 'ANTICIPOS',
     'label': 'Cuenta predeterminada para anticipos de clientes',
     'codigo_cuenta': '101020603'},
    {'tipo_operacion': 'ANTICIPO_PROVEEDOR', 'seccion': 'ANTICIPOS',
     'label': 'Cuenta predeterminada para anticipos a proveedores',
     'codigo_cuenta': '1010403'},
]
