from utils.db import db
from sqlalchemy.sql import func
import uuid

class Usuario(db.Model):
    __tablename__ = 'usuario'
    id_usuario = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    id_empresa = db.Column(db.String(36), db.ForeignKey('empresa.id_empresa', ondelete='RESTRICT'), nullable=False)
    id_perfil = db.Column(db.String(36), db.ForeignKey('perfil.id_perfil', ondelete='RESTRICT'), nullable=False)
    username = db.Column(db.String(50), nullable=False, unique=True)
    password_hash = db.Column(db.String(255), nullable=False)
    nombre_completo = db.Column(db.String(100))
    email = db.Column(db.String(128))
    estado = db.Column(db.Boolean, nullable=False, default=True)
    created_at = db.Column(db.DateTime, nullable=False, server_default=func.now())
    updated_at = db.Column(db.DateTime, nullable=False, server_default=func.now(), onupdate=func.now())
    # Campos tipo Dolibarr (alter_usuario_campos_dolibarr.sql)
    titulo_cortesia = db.Column(db.String(20))
    apellidos = db.Column(db.String(100))
    nombre = db.Column(db.String(100))
    administrador_sistema = db.Column(db.Boolean, default=False)
    sexo = db.Column(db.String(1))
    es_empleado = db.Column(db.Boolean, default=False)
    id_supervisor = db.Column(db.String(36), db.ForeignKey('usuario.id_usuario', ondelete='SET NULL'))
    id_validador_gastos = db.Column(db.String(36), db.ForeignKey('usuario.id_usuario', ondelete='SET NULL'))
    id_validador_dias_libres = db.Column(db.String(36), db.ForeignKey('usuario.id_usuario', ondelete='SET NULL'))
    usuario_externo = db.Column(db.Boolean, default=False)
    fecha_validez_desde = db.Column(db.Date)
    fecha_validez_hasta = db.Column(db.Date)
    direccion = db.Column(db.String(255))
    codigo_postal = db.Column(db.String(20))
    poblacion = db.Column(db.String(100))
    id_pais = db.Column(db.String(36), db.ForeignKey('pais.id_pais', ondelete='SET NULL'))
    id_provincia = db.Column(db.String(36), db.ForeignKey('provincia.id_provincia', ondelete='SET NULL'))
    telefono_trabajo = db.Column(db.String(30))
    movil = db.Column(db.String(30))
    fax = db.Column(db.String(30))
    codigo_contable = db.Column(db.String(50))
    color = db.Column(db.String(20))
    etiquetas_categorias = db.Column(db.String(255))
    idioma_default = db.Column(db.String(10))
    firma = db.Column(db.Text)
    nota_publica = db.Column(db.Text)
    nota_privada = db.Column(db.Text)
    puesto_trabajo = db.Column(db.String(100))
    tasa_hora = db.Column(db.Numeric(12, 2))
    tasa_dia = db.Column(db.Numeric(12, 2))
    salario = db.Column(db.Numeric(14, 2))
    horas_semana = db.Column(db.Numeric(5, 2))
    fecha_empleo_desde = db.Column(db.Date)
    fecha_empleo_hasta = db.Column(db.Date)
    fecha_nacimiento = db.Column(db.Date) 