from utils.db import db
from sqlalchemy.sql import func
import uuid


class Item(db.Model):
    __tablename__ = "item"
    __table_args__ = {"schema": "public"}

    id_item = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    id_empresa = db.Column(db.String(36), nullable=False)
    producto_ref = db.Column(db.String(255), nullable=False)
    etiqueta = db.Column(db.String(255), nullable=True)
    estado = db.Column(db.Boolean, nullable=False, default=True)
    descripcion = db.Column(db.Text, nullable=True)
    url_publica = db.Column(db.Text, nullable=True)
    peso = db.Column(db.Numeric(18, 6), nullable=True)
    longitud = db.Column(db.Numeric(18, 6), nullable=True)
    anchura = db.Column(db.Numeric(18, 6), nullable=True)
    altura = db.Column(db.Numeric(18, 6), nullable=True)
    superficie = db.Column(db.Numeric(18, 6), nullable=True)
    volumen = db.Column(db.Numeric(18, 6), nullable=True)
    nomenclatura_aduanera = db.Column(db.String(255), nullable=True)
    nota_interna = db.Column(db.Text, nullable=True)
    precio_venta = db.Column(db.Numeric(18, 6), nullable=True)
    precio_minimo = db.Column(db.Numeric(18, 6), nullable=True)
    impuesto_id = db.Column(db.String(255), nullable=True)
    created_at = db.Column(db.DateTime, nullable=False, server_default=func.now())
    updated_at = db.Column(db.DateTime, nullable=False, server_default=func.now(), onupdate=func.now())
    inventariable = db.Column(db.Boolean, nullable=False, default=True)
    duration_value = db.Column(db.Integer, nullable=True)
    mandatory_periods = db.Column(db.Boolean, nullable=True, default=False)
    created_by = db.Column(db.String(36), nullable=True)
    updated_by = db.Column(db.String(36), nullable=True)
    id_pais = db.Column(db.String(36), nullable=True)
    id_provincia = db.Column(db.String(36), nullable=True)
    poblacion = db.Column(db.String(255), nullable=True)
    id_unidad_medida = db.Column(db.String(36), nullable=True)
    id_unidad_peso = db.Column(db.String(36), nullable=True)
    id_unidad_longitud = db.Column(db.String(36), nullable=True)
    id_unidad_superficie = db.Column(db.String(36), nullable=True)
    id_unidad_volumen = db.Column(db.String(36), nullable=True)
    codigo_barras = db.Column(db.String(255), nullable=True)
    precio_compra = db.Column(db.Numeric(18, 6), nullable=True)
    stock_minimo_alerta = db.Column(db.Numeric(18, 6), nullable=True)
    stock_deseado = db.Column(db.Numeric(18, 6), nullable=True)
    id_almacen_defecto = db.Column(db.String(36), nullable=True)
    id_categoria_item = db.Column(db.String(36), nullable=True)
    id_estado_venta = db.Column(db.String(36), nullable=False)
    id_estado_compra = db.Column(db.String(36), nullable=True)
    id_tipo_control_caducidad = db.Column(db.String(36), nullable=True)
    id_tipo_item = db.Column(db.String(36), nullable=True)
    id_duration_unit = db.Column(db.String(36), nullable=True)
    id_tipo_control_inventario = db.Column(db.String(36), nullable=True)
    id_naturaleza_item = db.Column(db.String(36), nullable=False)
    id_tipo_comportamiento = db.Column(db.String(36), nullable=True)
    id_cuenta_venta = db.Column(db.String(36), nullable=True)
    id_cuenta_venta_intracomunitaria = db.Column(db.String(36), nullable=True)
    id_cuenta_venta_exportacion = db.Column(db.String(36), nullable=True)
    id_cuenta_compra = db.Column(db.String(36), nullable=True)
    id_cuenta_compra_intracomunitaria = db.Column(db.String(36), nullable=True)
    id_cuenta_compra_importacion = db.Column(db.String(36), nullable=True)
